### ISSUE TITLE
Load SIS data in the background when the app launches

### ISSUE THREAD

**Issue by hawkrives** [StoDevX/old-all-about-olaf#2]
or when the user taps on the SIS page, or...

**Comment by drewvolz** [comment]
This is a good idea because waiting is not very fun... but it will take a bit of thinking.  I grab the text from the view and save it, then login on that screen... if I am pulling it from the NSUserDefaults outside of the view, it will fail when they have changed their password (which is fine).  I'll draw it up and see if it works.
